// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/about": {
    params: {};
  };
  "/rating-ui": {
    params: {};
  };
  "/notes-app": {
    params: {};
  };
  "/simple-timer": {
    params: {};
  };
  "/cryptodash": {
    params: {};
  };
  "/cryptodash/:id": {
    params: {
      "id": string;
    };
  };
  "/shopping-cart-ui": {
    params: {};
  };
  "/portfolio": {
    params: {};
  };
  "/portfolio/:id": {
    params: {
      "id": string;
    };
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/about" | "/rating-ui" | "/notes-app" | "/simple-timer" | "/cryptodash" | "/cryptodash/:id" | "/shopping-cart-ui" | "/portfolio" | "/portfolio/:id";
  };
  "./routes/layouts/home.tsx": {
    id: "routes/layouts/home";
    page: "/";
  };
  "routes/pages/home/index.tsx": {
    id: "routes/pages/home/index";
    page: "/";
  };
  "./routes/layouts/normal.tsx": {
    id: "routes/layouts/normal";
    page: "/about";
  };
  "./routes/pages/about/index.tsx": {
    id: "routes/pages/about/index";
    page: "/about";
  };
  "./routes/layouts/project.tsx": {
    id: "routes/layouts/project";
    page: "/rating-ui" | "/notes-app" | "/simple-timer" | "/cryptodash" | "/cryptodash/:id" | "/shopping-cart-ui" | "/portfolio" | "/portfolio/:id";
  };
  "./routes/projects/rating-ui/index.tsx": {
    id: "routes/projects/rating-ui/index";
    page: "/rating-ui";
  };
  "./routes/projects/notes-app/index.tsx": {
    id: "routes/projects/notes-app/index";
    page: "/notes-app";
  };
  "./routes/projects/simple-timer/index.tsx": {
    id: "routes/projects/simple-timer/index";
    page: "/simple-timer";
  };
  "./routes/projects/cryptodash/index.tsx": {
    id: "routes/projects/cryptodash/index";
    page: "/cryptodash";
  };
  "./routes/projects/cryptodash/components/CoinDetails.tsx": {
    id: "routes/projects/cryptodash/components/CoinDetails";
    page: "/cryptodash/:id";
  };
  "./routes/projects/shopping-cart-ui/index.tsx": {
    id: "routes/projects/shopping-cart-ui/index";
    page: "/shopping-cart-ui";
  };
  "./routes/projects/portfolio/index.tsx": {
    id: "routes/projects/portfolio/index";
    page: "/portfolio";
  };
  "./routes/projects/portfolio/details.tsx": {
    id: "routes/projects/portfolio/details";
    page: "/portfolio/:id";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "routes/layouts/home": typeof import("./app/./routes/layouts/home.tsx");
  "routes/pages/home/index": typeof import("./app/routes/pages/home/index.tsx");
  "routes/layouts/normal": typeof import("./app/./routes/layouts/normal.tsx");
  "routes/pages/about/index": typeof import("./app/./routes/pages/about/index.tsx");
  "routes/layouts/project": typeof import("./app/./routes/layouts/project.tsx");
  "routes/projects/rating-ui/index": typeof import("./app/./routes/projects/rating-ui/index.tsx");
  "routes/projects/notes-app/index": typeof import("./app/./routes/projects/notes-app/index.tsx");
  "routes/projects/simple-timer/index": typeof import("./app/./routes/projects/simple-timer/index.tsx");
  "routes/projects/cryptodash/index": typeof import("./app/./routes/projects/cryptodash/index.tsx");
  "routes/projects/cryptodash/components/CoinDetails": typeof import("./app/./routes/projects/cryptodash/components/CoinDetails.tsx");
  "routes/projects/shopping-cart-ui/index": typeof import("./app/./routes/projects/shopping-cart-ui/index.tsx");
  "routes/projects/portfolio/index": typeof import("./app/./routes/projects/portfolio/index.tsx");
  "routes/projects/portfolio/details": typeof import("./app/./routes/projects/portfolio/details.tsx");
};