// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/about": {
    params: {};
  };
  "/rating-ui": {
    params: {};
  };
  "/notes-app": {
    params: {};
  };
  "/simple-timer": {
    params: {};
  };
  "/cryptodash": {
    params: {};
  };
  "/shopping-cart-ui": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/about" | "/rating-ui" | "/notes-app" | "/simple-timer" | "/cryptodash" | "/shopping-cart-ui";
  };
  "routes/home/index.tsx": {
    id: "routes/home/index";
    page: "/";
  };
  "./routes/about/index.tsx": {
    id: "routes/about/index";
    page: "/about";
  };
  "./routes/projects/rating-ui/index.tsx": {
    id: "routes/projects/rating-ui/index";
    page: "/rating-ui";
  };
  "./routes/projects/notes-app/index.tsx": {
    id: "routes/projects/notes-app/index";
    page: "/notes-app";
  };
  "./routes/projects/simple-timer/index.tsx": {
    id: "routes/projects/simple-timer/index";
    page: "/simple-timer";
  };
  "./routes/projects/cryptodash/index.tsx": {
    id: "routes/projects/cryptodash/index";
    page: "/cryptodash";
  };
  "./routes/projects/shopping-cart-ui/index.tsx": {
    id: "routes/projects/shopping-cart-ui/index";
    page: "/shopping-cart-ui";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "routes/home/index": typeof import("./app/routes/home/index.tsx");
  "routes/about/index": typeof import("./app/./routes/about/index.tsx");
  "routes/projects/rating-ui/index": typeof import("./app/./routes/projects/rating-ui/index.tsx");
  "routes/projects/notes-app/index": typeof import("./app/./routes/projects/notes-app/index.tsx");
  "routes/projects/simple-timer/index": typeof import("./app/./routes/projects/simple-timer/index.tsx");
  "routes/projects/cryptodash/index": typeof import("./app/./routes/projects/cryptodash/index.tsx");
  "routes/projects/shopping-cart-ui/index": typeof import("./app/./routes/projects/shopping-cart-ui/index.tsx");
};